# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    cmds:
      - docker compose build --progress=plain

  cli:
    cmds:
      - mkdir -p runtime && touch runtime/bash_history
      - xhost local:root
      - docker compose run --rm yolorun bash

  ultra:build:
    cmds:
      - docker compose build ultra --progress=plain

  ultra:
    cmds:
      - |
        mkdir -p runtime && touch runtime/bash_history
        xhost local:root
        # export UID="$(id -u)" 
        # export GID="$(id -g)"
        docker compose run --rm ultra bash


  trt:build:
    cmds:
      - docker compose build trt --progress=plain

  trt:
    cmds:
      - |
        mkdir -p runtime && touch runtime/bash_history
        xhost local:root
        # export UID="$(id -u)" 
        # export GID="$(id -g)"
        docker compose run --rm trt bash


  