# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    cmds:
      - docker compose build --progress=plain

  cli:
    cmds:
      - mkdir -p runtime && touch runtime/bash_history
      - xhost local:root
      - docker compose run --rm yolorun bash

  ultra:build:
    cmds:
      - docker compose build ultra --progress=plain

  ultra:
    cmds:
      - |
        mkdir -p runtime && touch runtime/bash_history_ultra
        xhost +local:root
        docker compose run --rm ultra bash


  trt:build:
    cmds:
      - docker compose build trt --progress=plain

  trt:
    cmds:
      - |
        mkdir -p runtime && touch runtime/bash_history_trt
        xhost +local:root || true
        docker compose run --rm trt bash

  models:
    cmds:
      - |
        mkdir -p models
        cd models
        wget https://github.com/Hyuto/yolov8-seg-onnxruntime-web/raw/master/public/model/nms-yolov8.onnx
        wget https://github.com/Hyuto/yolov8-seg-onnxruntime-web/raw/master/public/model/mask-yolov8-seg.onnx
        wget https://github.com/Hyuto/yolov8-seg-onnxruntime-web/raw/master/public/model/yolov8n-seg.onnx

  train:
    cmds:
      - yolo segment train data=/archive/dataset/plates-seg/plates-seg.yaml model=./models/yolov8n-seg.pt batch=-1 pretrained=true exist_ok=true epochs=100 imgsz=416 project=runs/plates-seg